# Generated by Django 5.0.3 on 2024-03-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

# dependencies means this migration file dependent on another migration file
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
