# Generated by Django 5.0.3 on 2024-03-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

# dependencies shows at which files it's dependent , if it get deleted then database will collapse
    dependencies = [
        ('home', '0003_alter_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
