# Generated by Django 5.0.3 on 2024-04-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_student_file_remove_student_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='feepaid',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
